# Autogenerated by nbdev

d = { 'settings': { 'branch': 'test_branch',
                'doc_baseurl': '/dnb_hub-nbdev',
                'doc_host': 'https://enjoki.github.io',
                'git_url': 'https://github.com/enjoki/dnb_hub-nbdev',
                'lib_path': 'dnb_hub_nbdev'},
  'syms': {'dnb_hub_nbdev.core': {'dnb_hub_nbdev.core.foo': ('core.html#foo', 'dnb_hub_nbdev/core.py')}}}
